import { readFileSync, writeFileSync } from 'node:fs';
import { deflateSync, inflateSync } from 'node:zlib';

export const PNG_SIGNATURE = Buffer.from([137,80,78,71,13,10,26,10]);
const crcTable = Array.from({ length: 256 }, (_, n) => { let c = n; for (let k=0;k<8;k++) c = (c & 1) ? (0xedb88320 ^ (c >>> 1)) : (c >>> 1); return c >>> 0; });
function crc32(buf){ let c=0xffffffff; for(const b of buf) c=crcTable[(c^b)&255]^(c>>>8); return (c^0xffffffff)>>>0; }
function chunk(type, data=Buffer.alloc(0)){ const t=Buffer.from(type); const out=Buffer.alloc(12+data.length); out.writeUInt32BE(data.length,0); t.copy(out,4); data.copy(out,8); out.writeUInt32BE(crc32(Buffer.concat([t,data])),8+data.length); return out; }

export function readPngRgba(path){ const file=readFileSync(path); if(file.length<8 || !file.subarray(0,8).equals(PNG_SIGNATURE)) throw new Error(`${path} must have a valid PNG signature`); let off=8, width=0,height=0,bit=0,color=0, idat=[], hasIhdr=false, hasIend=false, isFirstChunk=true; while(off<file.length){ if(off+12>file.length) throw new Error(`${path} contains a truncated PNG chunk`); const len=file.readUInt32BE(off); if(off+12+len>file.length) throw new Error(`${path} contains a truncated PNG chunk`); const type=file.toString('ascii',off+4,off+8); const data=file.subarray(off+8,off+8+len); const expected=file.readUInt32BE(off+8+len); if(crc32(Buffer.concat([Buffer.from(type),data]))!==expected) throw new Error(`${path} contains an invalid ${type} checksum`); off+=12+len; if(type==='IHDR'){ if(hasIhdr||len!==13) throw new Error(`${path} has an invalid IHDR chunk`); if(!isFirstChunk) throw new Error(`${path} IHDR must be the first chunk`); hasIhdr=true; width=data.readUInt32BE(0); height=data.readUInt32BE(4); bit=data[8]; color=data[9]; if(!width||!height) throw new Error(`${path} has invalid dimensions`); if(data[10]||data[11]||data[12]) throw new Error('Unsupported PNG compression/filter/interlace'); } else if(type==='IDAT'){ if(!hasIhdr) throw new Error(`${path} IDAT chunk before IHDR`); idat.push(data); } else if(type==='IEND'){ if(len!==0) throw new Error(`${path} IEND chunk must have length 0`); hasIend=true; break; } isFirstChunk=false; }
 if(off!==file.length) throw new Error(`${path} contains trailing data after IEND`); if(!hasIhdr||!hasIend||!idat.length) throw new Error(`${path} is not a complete PNG`); if(bit!==8 || ![2,6].includes(color)) throw new Error(`Unsupported PNG color type ${color} bit depth ${bit}`); const channels=color===6?4:3; const stride=width*channels; const decodedLength=(stride+1)*height; if(decodedLength>100*1024*1024) throw new Error(`${path} decoded size ${decodedLength} exceeds safety limit`); const raw=inflateSync(Buffer.concat(idat),{maxOutputLength:decodedLength}); if(raw.length!==(stride+1)*height) throw new Error(`${path} has an invalid decoded data length`); const rgba=Buffer.alloc(width*height*4); let src=0; const prev=Buffer.alloc(stride); let prior=Buffer.alloc(stride); for(let y=0;y<height;y++){ const filter=raw[src++]; const row=Buffer.from(raw.subarray(src,src+stride)); src+=stride; for(let x=0;x<stride;x++){ const a=x>=channels?row[x-channels]:0, b=prior[x], c=x>=channels?prior[x-channels]:0; if(filter===1) row[x]=(row[x]+a)&255; else if(filter===2) row[x]=(row[x]+b)&255; else if(filter===3) row[x]=(row[x]+Math.floor((a+b)/2))&255; else if(filter===4){ const p=a+b-c, pa=Math.abs(p-a), pb=Math.abs(p-b), pc=Math.abs(p-c); row[x]=(row[x]+(pa<=pb&&pa<=pc?a:pb<=pc?b:c))&255; } else if(filter!==0) throw new Error(`Unsupported PNG filter ${filter}`); }
 for(let x=0;x<width;x++){ const si=x*channels, di=(y*width+x)*4; rgba[di]=row[si]; rgba[di+1]=row[si+1]; rgba[di+2]=row[si+2]; rgba[di+3]=channels===4?row[si+3]:255; } prior=row; prev.fill(0); }
 return { width, height, data: rgba, colorType: color } }
export function writePngRgba(path, width, height, data){ const ihdr=Buffer.alloc(13); ihdr.writeUInt32BE(width,0); ihdr.writeUInt32BE(height,4); ihdr[8]=8; ihdr[9]=6; const stride=width*4; const raw=Buffer.alloc((stride+1)*height); for(let y=0;y<height;y++){ raw[y*(stride+1)]=0; Buffer.from(data.buffer,data.byteOffset+y*stride,stride).copy(raw,y*(stride+1)+1); } const png=Buffer.concat([PNG_SIGNATURE, chunk('IHDR',ihdr), chunk('IDAT',deflateSync(raw,{level:9})), chunk('IEND')]); writeFileSync(path,png); }
